definitions:
  payments.GetAllPaymentsResponse:
    properties:
      payments:
        items:
          $ref: '#/definitions/payments.GetPaymentResponse'
        type: array
    type: object
  payments.GetPaymentResponse:
    properties:
      amount:
        type: number
      created_at:
        type: string
      description:
        type: string
      id:
        type: string
      status:
        type: string
      updated_at:
        type: string
      user:
        type: string
    type: object
  payments.UpdatePaymentRequest:
    properties:
      id:
        type: string
      status:
        type: string
    type: object
  services.CreateParkingSpotRequest:
    properties:
      location:
        type: string
      name:
        type: string
    type: object
  services.ParkingSpot:
    properties:
      car:
        type: string
      location:
        type: string
      name:
        type: string
      occupied:
        type: boolean
      occupiedAt:
        type: string
    type: object
info:
  contact: {}
paths:
  /park:
    get:
      description: Get parking spots
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/services.ParkingSpot'
            type: array
      summary: Get parking spots
      tags:
      - parking
    post:
      consumes:
      - application/json
      description: Create parking spot
      parameters:
      - description: Create parking spot request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/services.CreateParkingSpotRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/services.ParkingSpot'
      summary: Create parking spot
      tags:
      - parking
  /park/{name}:
    get:
      description: Get parking spot
      parameters:
      - description: Parking spot name
        in: path
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/services.ParkingSpot'
      summary: Get parking spot
      tags:
      - parking
  /payments:
    get:
      description: Get all payments
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/payments.GetAllPaymentsResponse'
            type: array
      summary: Get all payments
      tags:
      - payments
  /payments/{id}:
    put:
      consumes:
      - application/json
      description: Update a payment
      parameters:
      - description: Payment ID
        in: path
        name: id
        required: true
        type: string
      - description: Payment
        in: body
        name: payment
        required: true
        schema:
          $ref: '#/definitions/payments.UpdatePaymentRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Update a payment
      tags:
      - payments
swagger: "2.0"
